services:
  stats-server:
    build: ./stats-server/service
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:16.1
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-service:
    build: ./ewm-service
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres