server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: validate  # Лучше использовать validate вместо update для продакшена
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
        connection:
          provider_disables_autocommit: true
    open-in-view: false  # Важно для корректной работы транзакций

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://stats-db:5432/stats?currentSchema=public
    username: stats
    password: stats
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2

  sql:
    init:
      mode: always  # Для инициализации через schema.sql
      schema-locations: classpath:schema.sql

  jackson:
    serialization:
      write-dates-as-timestamps: false
    format:
      datetime: yyyy-MM-dd'T'HH:mm:ss
    time-zone: UTC

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    ru.practicum: DEBUG
